package com.redstoner.nemes.redstone_sheep;

public enum Instruction {

	ADDWF, ANDWF, CLRF, CLRW, COMF, DECF, DECFSZ, INCF, INCFSZ, IORWF, MOVF, 
	MOVWF, NOP, RLF, RRF, SUBWF, SWAPF, XORWF, BCF, BSF, BTFSC, BTFSS, ADDLW, 
	ANDLW, CALL, CLRWDT, GOTO, IORLW, MOVLW, RETFIE, RETLW, RETURN, SLEEP, 
	SUBLW, XORLW, FADDWF, FCOMF, FDECF, FDECFSZ, FINCF, FINCFSZ, FSUBWF, FMULWF, 
	FDIVWF, FPTINT, INTTFP, FCOMPWF, MULWF, DIVWF, BOOL, STO, SHFTRN, SHFTLN, 
	SHFTRR, SHFTLR, COMPWF, LOADLW, GOTOF, SBAP, STTH, SPTH, LOCK, UNLOCK;
	
	public static final Instruction[] instructions = new Instruction[] {
			ADDWF, ANDWF, CLRF, CLRW, COMF, DECF, DECFSZ, INCF, INCFSZ, IORWF, MOVF,
			MOVWF, NOP, RLF, RRF, SUBWF, SWAPF, XORWF, BCF, BSF, BTFSC, BTFSS, ADDLW,
			ANDLW, CALL, CLRWDT, GOTO, IORLW, MOVLW, RETFIE, RETLW, RETURN, SLEEP,
			SUBLW, XORLW, FADDWF, FCOMF, FDECF, FDECFSZ, FINCF, FINCFSZ, FSUBWF, FMULWF,
			FDIVWF, FPTINT, INTTFP, FCOMPWF, MULWF, DIVWF, BOOL, STO, SHFTRN, SHFTLN,
			SHFTRR, SHFTLR, COMPWF, LOADLW, GOTOF, SBAP, STTH, SPTH, LOCK, UNLOCK
			};
}
